services:
  server:
    image: node:10.16-alpine
    container_name: reddit-api
    expose:
      - '4000'
    ports:
      - '4000:4000'
    volumes:
      - ./apps/reddit-clone-api:/usr/src/app/reddit-clone-api
    working_dir: /usr/src/app/reddit-clone-api
    links:
      - mongo
    command: sh -c 'tail -f /dev/null'
    
  client:
    image: node:10.16-alpine
    container_name: reddit-front
    expose:
      - '3000'
    volumes:
      - ./apps/reddit-clone-front:/usr/src/app/reddit-clone-front
    working_dir: /usr/src/app/reddit-clone-front
    ports:
      - '3000:3000'
    command: sh -c 'tail -f /dev/null'

  mongo:
    hostname: mongo
    image: mongo
    ports:
      - '27017:27017'
